pentaho-aggdesigner-core/build-res/subfloor.xml
pentaho-aggdesigner-ui/build-res/subfloor.xml

Merge of master into future-develop

Auto-Merge refreshing development branch

---

pentaho-aggdesigner-core/test-src/org/pentaho/aggdes/test/AllTests.java
pentaho-aggdesigner-core/test-src/org/pentaho/aggdes/test/MondrianSchemaLoaderTestIT.java
pentaho-aggdesigner-core/test-src/org/pentaho/aggdes/test/MondrianSchemaOutputTestIT.java
pentaho-aggdesigner-core/test-src/org/pentaho/aggdes/test/TableGeneratorTestIT.java

(cherry picked from commit 14e67d3)

[BACKLOG-5402] Split UT/IT for project: pentaho-aggdesigner-core

---

pentaho-aggdesigner-ui/test-src/org/pentaho/aggdes/ui/AggregateNamingServiceIT.java
pentaho-aggdesigner-ui/test-src/org/pentaho/aggdes/ui/AggregatePanelIT.java
pentaho-aggdesigner-ui/test-src/org/pentaho/aggdes/ui/AllTests.java

[BACKLOG-5383] Properly categorize unit tests and integration tests in

---

assemblies/pad-ce/assembly/resources/set-pentaho-env.bat
assemblies/pad-ce/assembly/resources/set-pentaho-env.sh
assemblies/pad-ce/assembly/resources/startaggregationdesigner.bat
assemblies/pad-ce/assembly/resources/startaggregationdesigner.sh
pentaho-aggdesigner-ui/dev-res/pad-dist.bat
pentaho-aggdesigner-ui/dev-res/pad-dist.sh

[PSW-229] Script files don't have an header with Copyright data

---

pentaho-aggdesigner-ui/src/main/resources-filtered/org/pentaho/aggdes/ui/resources/mainFrame.properties

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

assemblies/pad-ce/pom.xml
assemblies/pad-ce/src/main/resources-filtered/startaggregationdesigner.bat
assemblies/pad-ce/src/main/resources-filtered/startaggregationdesigner.sh
pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-ui/pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

pentaho-aggdesigner-ui/pom.xml

@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-commons-xul/pull/143

[BACKLOG-20423] Update downstreams

---

pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-ui/pom.xml

[BACKLOG-21650] - adds required jaxen lib

---

pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-core/src/main/java/org/pentaho/aggdes/model/ssas/ConversionUtil.java
pentaho-aggdesigner-ui/pom.xml

Cherry-pick of #93 into 7.1 branch.
@cravobranco @smmribeiro

[SP-4686] Backport of PPP-4182 - Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632 (7.1 Suite)

---

assemblies/pad-ce/src/main/resources-filtered/drivers/readme.txt

[PPP-4318] readme.txt file in Aggregation Designer tool is outdated

---

pentaho-aggdesigner-core/src/main/java/org/pentaho/aggdes/model/mondrian/MondrianDialect.java

@pentaho/tatooine @pentaho-lmartins

[PAD-97] - Invalid types in ddl generated for SQL Server

---

pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-core/src/main/java/org/pentaho/aggdes/model/mondrian/MondrianSchemaLoader.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/model/mondrian/ValidationMondrianSchemaLoaderTest.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/test/AllTests.java

@pentaho/tatooine @pentaho-lmartins

[PAD-147] - Cannot connect to Mondrian with SQL Server datasource using Integrated Security

---

pentaho-aggdesigner-core/src/main/java/org/pentaho/aggdes/model/mondrian/MondrianDialect.java

[SP-5224] Backport of PAD-97 - Invalid types in ddl generated for SQL Server (7.1 Suite)

---

pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-ui/pom.xml

[SP-6179][PPP-4654] Get commons-io version from parent pom

---

pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/AlgorithmImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/LatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MondrianSchemaOutputTestIT.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MonteCarloLatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/OutputServiceImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/TableGeneratorTestIT.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/output/impl/ResultHandlerStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/util/SerializationService.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/ResultHandlerStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AggControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AlgorithmRunnerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/DimensionRowModelTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/MainControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/SerializationServiceTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/exec/impl/JdbcTemplateSqlExecutorTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestUtils.java

@smmribeiro 
@bcostahitachivantara 
@renato-s

[PPP-4704] - Vulnerable Component: xstream-1.4.17

---

pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/AlgorithmImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/LatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MondrianSchemaOutputTestIT.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MonteCarloLatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/OutputServiceImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/TableGeneratorTestIT.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/output/impl/ResultHandlerStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/util/SerializationService.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/ResultHandlerStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AggControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AlgorithmRunnerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/DimensionRowModelTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/MainControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/SerializationServiceTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/exec/impl/JdbcTemplateSqlExecutorTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestUtils.java

@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6250] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.3 Suite)

---

pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/AlgorithmImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/LatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MondrianSchemaOutputTestIT.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MonteCarloLatticeImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/OutputServiceImplTest.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/TableGeneratorTestIT.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/output/impl/ResultHandlerStub.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-core/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/util/SerializationService.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AggregateStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/AlgorithmStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/ResultHandlerStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaLoaderStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/algorithm/impl/SchemaStub.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AggControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/AlgorithmRunnerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/DimensionRowModelTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/MainControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/SerializationServiceTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/exec/impl/JdbcTemplateSqlExecutorTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestUtils.java

@smmribeiro 
@renato-s 
@bcostahitachivantara

[SP-6251] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.4 Suite)

---

pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-ui/pom.xml

Reverts pentaho/pentaho-aggdesigner#172

Revert "[PPP-4802] -  Vulnerable Component: hsqldb"

---

.gitignore
pentaho-aggdesigner-core/pom.xml
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/MondrianSchemaOutputTestIT.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/TableGeneratorTestIT.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/util/TestAggregate.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/util/TestResult.java
pentaho-aggdesigner-core/src/it/java/org/pentaho/aggdes/test/util/TestUtils.java
pentaho-aggdesigner-ui/pom.xml
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/ui/MainControllerTest.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestAggregate.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestResult.java
pentaho-aggdesigner-ui/src/test/java/org/pentaho/aggdes/util/TestUtils.java
pom.xml

@bcostahitachivantara @renato-s @andreramos89

[BACKLOG-38674] Integration Tests are outdated and some do not compile.

---

pentaho-aggdesigner-ui/pom.xml
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/form/controller/AggController.java
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/form/controller/ExportHandler.java

[BACKLOG-42741]-Upgrading pentaho-aggdesigner from Java EE to Jakarta EE
[BACKLOG-42741]: https://hv-eng.atlassian.net/browse/BACKLOG-42741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42741]-Upgrading pentaho-aggdesigner from Java EE to Jakarta EE

---

pentaho-aggdesigner-ui/pom.xml
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/form/controller/AggController.java
pentaho-aggdesigner-ui/src/main/java/org/pentaho/aggdes/ui/form/controller/ExportHandler.java

This pull request primarily updates dependencies in the `pom.xml` file and replaces the `@Required` annotation with `@Autowired` in several Java classes to align with modern Spring practices. These changes improve compatibility and streamline dependency injection.
* [`pentaho-aggdesigner-ui/pom.xml`](diffhunk://#diff-44065013f41ed68ec2127f11931e9006517e656910de7f469402b87f42d92f8cL404-R406): Updated Jersey dependencies from `com.sun.jersey` to `org.glassfish.jersey` equivalents and replaced `javax.ws.rs` with `jakarta.ws.rs`. This modernizes the project dependencies and introduces version variables for better maintainability. [[1]](diffhunk://#diff-44065013f41ed68ec2127f11931e9006517e656910de7f469402b87f42d92f8cL404-R406) [[2]](diffhunk://#diff-44065013f41ed68ec2127f11931e9006517e656910de7 …

[BACKLOG-40823] - Upgrade the Tomcat version from current to 10.x.x with Java 17
